# Generated by Django 5.2.4 on 2026-01-09 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_analysis', models.CharField(choices=[('ndvi', 'NDVI'), ('evi', 'EVI'), ('ndwi', 'NDWI')], max_length=20)),
                ('default_date_days', models.PositiveIntegerField(default=14)),
                ('default_comparison', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
