# Generated by Django 5.2.4 on 2026-01-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_analysis',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('ndmi', 'NDMI')], max_length=20),
        ),
    ]
