# Generated by Django 5.2.4 on 2026-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usersettings_default_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_analysis',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('ndmi', 'NDMI')], default='ndvi', max_length=20),
        ),
    ]
