# Generated by Django 5.2.4 on 2025-10-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('analysis_type', models.CharField(choices=[('ndvi', 'NDVI'), ('evi', 'EVI'), ('ndwi', 'NDWI')], max_length=10)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('compare_start_date', models.DateField(blank=True, null=True)),
                ('compare_end_date', models.DateField(blank=True, null=True)),
                ('comparison', models.BooleanField(default=False)),
                ('celery_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('result_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
