# Generated by Django 5.2.4 on 2025-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='largest_nan_frac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='pct_nans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='qc_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='qc_warning',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
