# Generated by Django 5.2.4 on 2025-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysistask_largest_nan_frac_analysistask_pct_nans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='error_msg',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
