# Generated by Django 5.2.4 on 2025-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysistask_error_code_analysistask_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='error_msg',
            field=models.CharField(blank=True, default=''),
        ),
    ]
