# Generated by Django 5.2.4 on 2026-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysistask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='analysis_type',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('ndmi', 'NDMI')], max_length=10),
        ),
    ]
