# Generated by Django 5.2.4 on 2026-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_analysistask_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='ai_insight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
