# Generated by Django 5.2.4 on 2026-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_analysistask_ai_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='analysis_type',
            field=models.CharField(choices=[('ndvi', 'NDVI'), ('ndmi', 'NDMI')], max_length=16),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='result_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='PENDING', max_length=50),
        ),
    ]
